name: Build, Push and Deploy to Production Server

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    branches:
      - '*'
    

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    DOCKER_NAME: jeffstjean/oweek_nodejs:prod
    DOCKER_PATH: ./api
    DEPLOY_NAME: oweek_prod
    DEPLOY_PATH: /home/jeff/oweek-prod

jobs:
    build-push-deploy:
        name: Build, Push and Deploy
        runs-on: ubuntu-latest

        steps:
            
        - name: Checkout
          uses: actions/checkout@v2 

        - name: Login to docker
          run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

        - name: Build api docker image
          run: docker build -t $DOCKER_NAME $DOCKER_PATH

        - name: Push api docker image
          run: docker push $DOCKER_NAME

        # testing passing envs to other 'with' params (DEPLOY_PATH)
        - name: Pull from git
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.DEPLOY_HOST }}
            username: ${{ secrets.DEPLOY_USER }}
            key: ${{ secrets.DEPLOY_KEY }}
            envs: DEPLOY_PATH 
            script: git -C $DEPLOY_PATH pull
          
        - name: Deploy to remote server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.DEPLOY_HOST }}
            username: ${{ secrets.DEPLOY_USER }}
            key: ${{ secrets.DEPLOY_KEY }}
            envs: DEPLOY_PATH,DEPLOY_NAME
            script: docker stack deploy -c $DEPLOY_PATH/docker-compose.yml -c $DEPLOY_PATH/docker-compose.prod.yml $DEPLOY_NAME

